language: go
sudo: required

go:
  - 1.x

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - dep ensure
  - GOOS=linux GOARCH=amd64 go build -tags netgo -o timtam-receiver server.go

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t timtam-receiver .
  - docker images
  - docker tag timtam-receiver $DOCKER_USERNAME/timtam-receiver
  - docker push $DOCKER_USERNAME/timtam-receiver